name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        
    - name: Install depdendencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy
      uses: rdarida/simple-github-pages-deploy-action@v1
      with:
        git-base-folder: dist
        commit-message: Compiled client
        branch: pages
    
